
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - internal

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:

